### PR TITLE
Initial PR

### PR DESCRIPTION
**Pull request by krallin**

### CODE REVIEW

**Comment by krallin** [comment]
@fancyremarker if you'd like to take a look at this, this is the (still a bit WIP, I'm working on adding more test coverage) code for the metric collector and aggregator (it's the same code base for both since they're sharing some components). I can walk you through it if you'd like!

**Comment by fancyremarker** [comment]
Thank you @krallin ! A walkthrough would be very helpful for me here, actually. I'll ping you tomorrow morning to see when works for you.

**Comment by krallin** [comment]
@fancyremarker FYI , I made a number of new changes here:

- Added Datadog support
- Added a short hostname
- Added some backoff before retrying

And improved the code in a variety of places (e.g. auto-generating the "entry to InfluxDB" and "entry to Datadog" formatters using the protobuf definition, which ensures they'll keep up to date on their own).

**Comment by krallin** [comment]
There's just a couple of outstanding items here, which I'll address when I return from vacation:

- [ ] Publish I/O (bytes / ops).
- [ ] Don't publish unavailable metrics (disks when we don't have a mount).
- [ ] Use codegen for the CgroupPoint -> api.PublishRequest conversion, to ensure we don't miss any points there.

**Pull request merged**
